let usuarios = [
  {
    first_name: 'Marta',
    last_name: 'Hernandez',
    age: 56,
    hobbies: ['Cocinar', 'Bailar'],
    active: true,
  },
  {
    first_name: 'Jose',
    last_name: 'Perez',
    age: 32,
    hobbies: ['Poesia', 'Leer'],
    active: true,
  },
  {
    first_name: 'Carlos',
    last_name: 'Fernandez',
    age: 12,
    hobbies: ['Bailar', 'Cantar'],
    active: true,
  },
  {
    first_name: 'Ramon',
    last_name: 'Niño',
    age: 35,
    hobbies: ['Cocinar', 'Dibujar'],
    active: true,
  },
  {
    first_name: 'Pedro',
    last_name: 'Panizzo',
    age: 87,
    hobbies: ['Poesia', 'Escribir'],
    active: true,
  },
  {
    first_name: 'Enrique',
    last_name: 'Lopez',
    age: 64,
    hobbies: ['Bailar', 'Poesia'],
    active: false,
  },
  {
    first_name: 'Juan',
    last_name: 'Urbina',
    age: 19,
    hobbies: ['Leer', 'Cantar'],
    active: false,
  },
  {
    first_name: 'Ismael',
    last_name: 'Gomez',
    age: 33,
    hobbies: ['Cocinar', 'Bailar'],
    active: true,
  },
  {
    first_name: 'Eddy',
    last_name: 'Orozco',
    age: 21,
    hobbies: ['Cantar', 'Dibujar'],
    active: true,
  },
  {
    first_name: 'Marcos',
    last_name: 'Campos',
    age: 37,
    hobbies: ['Leer', 'Escribir'],
    active: false,
  },
]